export const list = [
    {
        cover: 'test/avatar/4403/cover.png',
        gender: '男',
        id: 4403,
        name: '测试2勿动男',
        play: 'test/video/16196',
        portrait: 'test/avatar/4403/preview_head.jpg',
        preview: 'test/avatar/4403/preview_img.png',
        preview_half: 'test/avatar/4403/preview_half.jpg',
        takeover: 'test/video/16195/outputa.mp4',
    },
    {
        cover: null,
        gender: '女',
        id: 4402,
        name: '测试1勿动女',
        play: 'test/video/16094',
        portrait: 'test/avatar/4402/preview_head.jpg',
        preview: 'test/avatar/4402/preview_img.png',
        preview_half: 'test/avatar/4402/preview_half.jpg',
        takeover: 'test/video/16093/outputa.mp4',
    },
    {
        cover: 'test/avatar/4398/cover.png',
        gender: '女',
        id: 4398,
        name: '青春',
        play: 'test/video/16053',
        portrait: 'test/avatar/4398/preview_head.jpg',
        preview: 'test/avatar/4398/preview_img.png',
        preview_half: 'test/avatar/4398/preview_half.png',
        takeover: 'test/video/16052/outputa.mp4',
    },
    {
        cover: 'test/avatar/3691/cover.png',
        gender: '男',
        id: 3691,
        name: '男灰西装半身绿幕',
        play: 'test/video/16028',
        portrait: 'test/avatar/3691/preview_head.jpg',
        preview: 'test/avatar/3691/preview_img_397.png',
        preview_half: 'test/avatar/3691/preview_half.jpg',
        takeover: 'test/video/16027/outputa.mp4',
    },
    {
        cover: 'test/avatar/3688/cover.png',
        gender: '女',
        id: 3688,
        name: '女红裙绿幕',
        play: 'test/video/16169',
        portrait: 'test/avatar/3688/preview_head.jpg',
        preview: 'test/avatar/3688/preview_img_738.png',
        preview_half: 'test/avatar/3688/preview_half.jpg',
        takeover: 'test/video/16168/outputa.mp4',
    },
    {
        cover: 'test/avatar/4211/cover.png',
        gender: '女',
        id: 4211,
        name: '新版柒柒8506',
        play: 'test/video/14042',
        portrait: 'test/avatar/4074/preview_head.jpg',
        preview: 'test/avatar/4074/preview_img.png',
        preview_half: 'avatar/4074/preview_half.png',
        takeover: 'test/video/14041/outputa.mp4',
    },
    {
        cover: 'test/avatar/4212/cover.png',
        gender: '女',
        id: 4212,
        name: '新版希希8520',
        play: 'test/video/16081',
        portrait: 'test/avatar/4075/preview_head.jpg',
        preview: 'test/avatar/4075/preview_img.png',
        preview_half: 'avatar/4075/preview_half.png',
        takeover: 'test/video/16080/outputa.mp4',
    },
    {
        cover: 'test/avatar/3718/cover.png',
        gender: '女',
        id: 3718,
        name: '沙发背景',
        play: 'test/video/9657',
        portrait: 'test/avatar/3718/preview_head.jpg',
        preview: 'test/avatar/3718/preview_img_35.png',
        preview_half: 'test/avatar/3718/preview_half.jpg',
        takeover: 'test/video/9706/outputa.mp4',
    },
    {
        cover: 'test/avatar/4071/cover.png',
        gender: '女',
        id: 4071,
        name: '新版隋欣然医生',
        play: 'test/video/14040',
        portrait: 'test/avatar/4066/preview_head.jpg',
        preview: 'test/avatar/3716/preview_img_704.png',
        preview_half: 'test/avatar/4066/preview_half.jpg',
        takeover: 'test/video/14039/outputa.mp4',
    },
    {
        cover: 'test/avatar/3690/cover.png',
        gender: '男',
        id: 3690,
        name: '男灰西装桌子绿幕',
        play: 'test/video/6677',
        portrait: 'test/avatar/3690/preview_head.jpg',
        preview: 'test/avatar/3690/preview_img_716.png',
        preview_half: 'test/avatar/3690/preview_half.jpg',
        takeover: 'test/video/11354/outputa.mp4',
    },
    {
        cover: 'test/avatar/3716/cover.png',
        gender: '女',
        id: 3716,
        name: '医生背景',
        play: 'test/video/16824',
        portrait: 'test/avatar/3716/preview_head.jpg',
        preview: 'test/avatar/3716/preview_img_704.png',
        preview_half: 'test/avatar/3716/preview_half.jpg',
        takeover: 'test/video/16823/outputa.mp4',
    },
    {
        cover: 'test/avatar/3715/cover.png',
        gender: '女',
        id: 3715,
        name: '客服背景111',
        play: 'test/video/6697',
        portrait: 'test/avatar/3715/preview_head.jpg',
        preview: 'test/avatar/3715/preview_img_894.png',
        preview_half: 'test/avatar/3715/preview_half.jpg',
        takeover: 'test/video/7955/outputa.mp4',
    },
    {
        cover: 'test/avatar/3714/cover.png',
        gender: '女',
        id: 3714,
        name: '黑白连衣裙律师背景',
        play: 'test/video/11428',
        portrait: 'test/avatar/3714/preview_head.jpg',
        preview: 'test/avatar/3714/preview_img_484.png',
        preview_half: 'test/avatar/3714/preview_half.jpg',
        takeover: 'test/video/11427/outputa.mp4',
    },
    {
        cover: 'test/avatar/3713/cover.png',
        gender: '女',
        id: 3713,
        name: '律师黑白连衣裙',
        play: 'test/video/9655',
        portrait: 'test/avatar/3713/preview_head.jpg',
        preview: 'test/avatar/3713/preview_img_297.png',
        preview_half: 'test/avatar/3713/preview_half.png',
        takeover: 'test/video/9654/outputa.mp4',
    },
    {
        cover: 'test/avatar/3712/cover.png',
        gender: '女',
        id: 3712,
        name: '律师绿幕',
        play: 'test/video/6694',
        portrait: 'test/avatar/3712/preview_head.jpg',
        preview: 'test/avatar/3712/preview_img_558.png',
        preview_half: 'test/avatar/3712/preview_half.jpg',
        takeover: '',
    },
    {
        cover: 'test/avatar/3703/cover.png',
        gender: '女',
        id: 3703,
        name: '女黄裙桌子',
        play: 'test/video/6690',
        portrait: 'test/avatar/3703/preview_head.jpg',
        preview: 'test/avatar/3703/preview_img_989.png',
        preview_half: 'test/avatar/3703/preview_half.png',
        takeover: 'test/video/7973/outputa.mp4',
    },
    {
        cover: 'test/avatar/3702/cover.png',
        gender: '男',
        id: 3702,
        name: '男黑西装全身',
        play: 'test/video/15008',
        portrait: 'test/avatar/3702/preview_head.jpg',
        preview: 'test/avatar/3702/preview_img_740.png',
        preview_half: 'test/avatar/3702/preview_half.png',
        takeover: 'test/video/7974/outputa.mp4',
    },
    {
        cover: 'test/avatar/3701/cover.png',
        gender: '男',
        id: 3701,
        name: '男灰马甲半身',
        play: 'test/video/10988',
        portrait: 'test/avatar/3701/preview_head.jpg',
        preview: 'test/avatar/3701/preview_img_925.png',
        preview_half: 'test/avatar/3701/preview_half.png',
        takeover: 'test/video/10987/outputa.mp4',
    },
    {
        cover: 'test/avatar/3700/cover.png',
        gender: '男',
        id: 3700,
        name: '男灰西装半身',
        play: 'test/video/12095',
        portrait: 'test/avatar/3700/preview_head.jpg',
        preview: 'test/avatar/3700/preview_img_663.png',
        preview_half: 'test/avatar/3700/preview_half.png',
        takeover: 'test/video/12094/outputa.mp4',
    },
    {
        cover: 'test/avatar/3699/cover.png',
        gender: '男',
        id: 3699,
        name: '男白色衬衫坐姿',
        play: 'test/video/9624',
        portrait: 'test/avatar/3699/preview_head.jpg',
        preview: 'test/avatar/3699/preview_img_694.png',
        preview_half: 'test/avatar/3699/preview_half.png',
        takeover: 'test/video/9623/outputa.mp4',
    },
    {
        cover: 'test/avatar/3696/cover.png',
        gender: '女',
        id: 3696,
        name: '女黄衬衫半身绿幕',
        play: 'test/video/12051',
        portrait: 'test/avatar/3696/preview_head.jpg',
        preview: 'test/avatar/3696/preview_img_455.png',
        preview_half: 'test/avatar/3696/preview_half.jpg',
        takeover: 'test/video/12050/outputa.mp4',
    },
    {
        cover: 'test/avatar/3689/cover.png',
        gender: '男',
        id: 3689,
        name: '男白色衬衫坐姿绿幕',
        play: 'test/video/6676',
        portrait: 'test/avatar/3689/preview_head.jpg',
        preview: 'test/avatar/3689/preview_img_125.png',
        preview_half: 'test/avatar/3689/preview_half.jpg',
        takeover: 'test/video/11349/outputa.mp4',
    },
    {
        cover: 'test/avatar/3694/cover.png',
        gender: '女',
        id: 3694,
        name: '女黄裙桌子绿幕',
        play: 'test/video/12101',
        portrait: 'test/avatar/3694/preview_head.jpg',
        preview: 'test/avatar/3694/preview_img_768.png',
        preview_half: 'test/avatar/3694/preview_half.jpg',
        takeover: 'test/video/12100/outputa.mp4',
    },
];
